### ISSUE TITLE
Request Google Drive Link to download VT-MOT Dataset

### ISSUE THREAD

**Issue by MMarvasti** [wqw123wqw/PFTrack#3]
Could you please share an alternative link, such as Google Drive, for your VT-MOT dataset?

**Comment by NeverBehave** [comment]
If you really cannot download via Magnet link listed in #1 , here is a direct download link: https://stor-001.static.mtrd.in/dataset/PFTrack/

It might be taken down at anytime tho.

**Comment by MMarvasti** [comment]
Thank you

**Comment by AAleksandros** [comment]
> If you really cannot download via Magnet link listed in #1 , here is a direct download link: https://stor-001.static.mtrd.in/dataset/PFTrack/
> 
> It might be taken down at anytime tho.

As of today it still works, I was able to download the 2 archives (test/train) through the links. I will also have to mention that the magnet does work, it just takes a while to start downloading. 

Thanks a lot @NeverBehave, this dataset is invaluable.
